### ISSUE TITLE
Community contributions

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#17]
As discussed by email, @sneumann will maintain metabolomics images and I will for proteomics images, and we will push to this repository. How is it for the docker hub? Are these pushed/tested automatically as part of the Bioconductor account?

Should we then user our own accounts for any images that are not (yet) under the Bioconductor hub?

**Comment by lgatto** [comment]
How do community contributions work with [Bioconductor's docker hub](https://hub.docker.com/u/bioconductor/)? Is whatever we push via a PR propagated to the hub? Should be put additional containers to our own hubs, or to Bioconductor's?

**Comment by lshep** [comment]
I will set up new repositories on bioconductor's docker hub that will automatically build upon pushes to the repository.  

So example for devel:

Bioconductor/devel_base2
Bioconductor/devel_core2 

I will set up in the next day 
Bioconductor/devel_metabolomics2
Bioconductor/devel_protmetcore2

And similarly for release. 

It is possible to link docker repositories together to be build if one docker image changes; this is how I have set up core2 to build when there is a successful build of base2. Similarly I will set it up so that on a successful rebuild of core2, protmetcore2 will build and when that is successful, metabolomics2 to build. 

The release we will only build at the time of Bioconductor release dates and only if we are aware of some large change. These I will trigger manually on dockerhub. 

The devel will be built weekly.

**Comment by lgatto** [comment]
Could you clarify what the 2 suffix stands for.

**Comment by lshep** [comment]
We changed the way the bioconductor docker hub repositories work and want them to automatically build. Once you set up a repository it seems you are unable to change the way it is set up. All the current repository (devel_base, etc) were set up to not automatically build but were built elsewhere and uploaded.  We didn't want to destroy the old repositories and felt it was useful to keep there history but essentially they will all become legacy.   
So the 2 distinguishes the currently used, and frequently updated respositories

**Comment by lshep** [comment]
I just created protmetcore2 and metabolomics docker repositories and am kicking off initial builds.  @sneumann I'll keep you updated if there are any issues. 

Please note if you would like the [date tags](https://hub.docker.com/r/bioconductor/devel_core2/tags/) in addition to latest, please add the hooks directory found in src/core/hooks.  Otherwise the docker with keep overwriting latest.

**Comment by lgatto** [comment]
Thank you for clarifying the `2` suffix. 

How would you see the addition of new containers. For example, I have a container that also installs all the suggested packages to be able to fully run a vignette. Should I add these to my own docker hub or could these be added to the Bioconductor hub?

**Comment by lgatto** [comment]
Also, I am considering using a more lightweight `mscore` container (see issue #14), as I think it is a better (lighter) option to build paper/application specific containers. Would it be fine to add it to Bioconductor? 

I have an forked repo that (apart from using the containers marked as `2`) I could send a pull request for.

**Comment by lshep** [comment]
We would recommend and prefer that they be added to Bioconductor.  Do you have the ability to add a Bioconductor container on DockerHub?  If not we can make it possible for you to.  
Yes you can send a pull request to add it to Bioconductor and I will look it over; provided it doesn't change any of our core functionality it should be fine.  Note: if you are basing your core off of Bioconductor base, it should probably be based of the container marked 2 as that will be the updated containers.

**Comment by lgatto** [comment]
> We would recommend and prefer that they be added to Bioconductor. Do you have the ability to add a Bioconductor container on DockerHub? If not we can make it possible for you to.

I don't think I can. I am happy to be given permission to do so or for you to do it. Whatever suites you best.

> [...] it should probably be based of the container marked 2 as that will be the updated containers.

Yes, I will make sure to use these.

I will update my containers accordingly and do a bit of clean-up before sending the PR, probably next week or so.

**Comment by mtmorgan** [comment]
I added @lgatto as a collaborator with write access.

**Comment by lgatto** [comment]
@lshep - as far as I understand, when you merge a PR, this triggers a re-build of the containers on the docker hub, and once a core container is updated and build successfully, say `mscore`, then it's depending container (say `proteomics`) will be build too. 

Is this correct?

Are there any other delays before which to build and/or updates on the docker hub are triggers?

**Comment by lshep** [comment]
No it does not trigger a build immediately.  Plus, the past pull requests have only been in the src directory and would not have reflected the change without first performing the rake.  The trigger for the Bioconductor devel base container is on a new pushed tag not on any commit.  It gets built weekly as there is code run to rake the github repository and to push a new tag with the date.  The other devel  containers get built when the container they are based on is successfully built.  so devel core will be build again once devel base is built successfully, and down the line with the parents/children.    
The release ones we do not want rebuilt weekly unless a major change to them for stability and the fact that release packages shouldn't change much.  

I'm triggering devel builds manually so that yours that have not been built can get built right away rather than waiting until monday when they will be triggered automatically.

**Comment by lgatto** [comment]
Ok, thanks. Is that convenient for you? Or would it be better for me to be able to trigger the rebuild directly? Otherwise, I could think of mirroring the containers in my personal docker hub for testing, and then send a PR. My only problem with that is that `mscore` and `proteomics` would live in 2 docker hubs.

**Comment by lshep** [comment]
It's fine; I don't mind.  Once its on I just go to the dockerhub container and trigger. Its up to you however you would like to handle it as long as the correct code eventually gets on github so the Bioconductor containers get updated.  If you are able to rake the file on your system to commit the src and the updated out files that would be helpful tho.   

I need to modify the rake file to force the files in the out to be rebuild;  I noticed a bug in that if the files exist it doesn't update/overwrite.  I hopefully will have this fixed shortly.

**Comment by lshep** [comment]
actually it looks like i was wrong about the files not updating on the rake so we should be good.
