### ISSUE TITLE
Online and offline parent containers

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#29]
The latest `mscore` built successfully, and `proteomics` is currently being re-built - fingers crossed. I haven't managed to do a good job at testing my changes locally because `proteomics` depends on `mscore` that is fetched from the docker hub. Here is a description 

1. I identify that I need to add `libx11-dev` to the failing container for an R package to build. Adding this new apt-get dependency to `proteomics` allows me to build the container locally. 
2. But I would prefer that dependency to be added to the parent container `mscore`. I make the change there and build it successfully locally.
3. How can I test `proteomics` so that it uses the locally built `mscore` (step 2) rather then fetch `bioconductor/proteomics` from docker hub.

Without being able to test step 3, I need to wait that the containers get updated remotely before being sure that the child container effectively builds/works. 

@lshep @sneumann - Any idea how to address my question in step 3?

**Comment by lshep** [comment]
I'm pretty sure if you build your docker locally calling it the parent name i.e  docker build -t  bioconductor/devel_mscore2 that when you go to build proteomics it will use the local copy and not fetch a new version... 

You could also run the container docker run -t -i bioconductor/devel_mscore2  /bin/bash and add whatever additional dependencies manually first and start R to see if the install of packages  from the proteomics install script works... not ideal since its all manually but serves its purpose.

**Comment by lgatto** [comment]
Thank you @lshep - I thought I tried setting the tag but didn't seem to work. I'll know soon enough, when the the [`proteomics2` build status](https://hub.docker.com/r/bioconductor/release_proteomics2/builds/) comes up.
