### ISSUE TITLE
install libpng-dev

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioc_docker#66]
https://github.com/Bioconductor/bioc_docker/blob/072c4e4a412a0cdad5be991a492f4869fe187a48/src/core/Dockerfile.in#L8

Not sure if that's the right place to do it, but can we add libpng-dev to the Dockerfile files? It's a lightweight addition that some popular package depend on.  E.g.:

`RUN apt-get install -y libpng-dev`

**Comment by lshep** [comment]
probably better to put it in base - I think that's where we put these types of system dependency -  I'll look at adding this this week.

**Comment by lshep** [comment]
For the record:  This was not in the original list of system dependencies because it is not needed in the list of package we provide by default. technically it should not be added for this reason with the idea that if you wanted to add on packages, you would add them on your own including any system dependencies for those additional packages - keeping the base images with only necessities.  We will rethink this policy and request like this will be decided on a 'case by case' basis.
  
In this case we will add this dependency. I'll look at making the change sometime this week.

**Comment by lshep** [comment]
These should now be in the devel and release base/core

**Comment by lwaldron** [comment]
Thanks @lshep!
